name: moor_shared
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dart
  cupertino_icons: ^0.1.3
  moor: ^3.1.0
  rxdart: ^0.22.2
  intl: ^0.16.0

  # Database for mobile and Desktop
  moor_ffi: ^0.6.0
  
  # Helper to find the database path on mobile
  path_provider: 
  path: 

  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: b9c7e27ba16f86ff3390cfb0e460802e9980399a
  

  # Web

dev_dependencies:
  moor_generator: ^3.1.0
  build_runner: 
  build_web_compilers: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
